#include "levels/pgy/texture_include.inc.c"
#include "levels/pgy/area_1/collision.inc.c"
#include "levels/pgy/area_1/room.inc.c"
#include "levels/pgy/area_1/macro.inc.c"
#include "levels/pgy/area_1/spline.inc.c"
#include "levels/pgy/model.inc.c"
