extern const GeoLayout pgy_area_1_geo[];
extern const GeoLayout pgy_area_1[];
extern const Collision pgy_area_1_collision[];
extern const MacroObject pgy_area_1_macro_objs[];
extern u8 pgy_dl_treasure_chest_lock_top_rgba16_rgba16[];
extern u8 pgy_dl_treasure_chest_side_rgba16_rgba16[];
extern Vtx pgy_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx pgy_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx pgy_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx pgy_dl_skinned_mesh_layer_1_vtx_cull[8];
extern Vtx pgy_dl_skinned_mesh_layer_1_vtx_0[163];
extern Gfx pgy_dl_skinned_mesh_layer_1_tri_0[];
extern Gfx mat_pgy_dl_sm64_material_001[];
extern Gfx mat_revert_pgy_dl_sm64_material_001[];
extern Gfx mat_pgy_dl_f3dlite_material[];
extern Gfx mat_revert_pgy_dl_f3dlite_material[];
extern Gfx pgy_dl_Cube_mesh_layer_1[];
extern Gfx pgy_dl_skinned_mesh_layer_1[];
